# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VobjectsObjectNameActionsMergePostRequestInner")
invisible(lapply(list.files(file.path("..", "..", "R"), full.names = TRUE), source))

model_instance <- VobjectsObjectNameActionsMergePostRequestInner$new()

test_that("duplicate_record_id", {
  # tests for the property `duplicate_record_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`duplicate_record_id`, "EXPECTED_RESULT")
})

test_that("main_record_id", {
  # tests for the property `main_record_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`main_record_id`, "EXPECTED_RESULT")
})
